window.SITE_DATA = {
  meta: {
    name: "Angelos Fikias",
    role: "Platform Engineer",
    company: "Dataviva",
    location: "Thessaloniki, Greece",
    email: "angelosfikias@gmail.com",
    github: "https://github.com/AngelosFikias0",
    linkedin: "https://www.linkedin.com/in/angelos-fikias/",
    status: "Shipping production infrastructure",
    focus: "Platform Engineering · DevOps · Cloud Infrastructure",
    openTo: "Platform / SRE / DevOps roles",
  },

  terminal: [
    { type: "cmd", text: "cat whoami.json" },
    { type: "blank" },
    { type: "brace", text: "{" },
    { type: "field", key: "name", value: "Angelos Fikias" },
    { type: "field", key: "role", value: "Associate Platform Engineer" },
    { type: "field", key: "company", value: "Dataviva" },
    { type: "field", key: "location", value: "Thessaloniki, Greece" },
    {
      type: "field",
      key: "focus",
      value: "Platform Engineering · DevOps · Cloud Infrastructure",
    },
    {
      type: "field",
      key: "education",
      value: "BSc Applied CS @ University of Macedonia",
      last: true,
    },
    { type: "brace", text: "}" },
  ],

  hero: {
    headline: ["Building ", "platforms", " that\nship with confidence."],
    sub: "Platform engineer focused on cloud-native infrastructure, automation, and scalable system architecture. I design and build platforms for high reliability, performance, and long-term evolution - end to end.",
    ctas: [
      { label: "$ explore --projects", href: "#projects", style: "primary" },
      {
        label: "$ open github",
        href: "https://github.com/AngelosFikias0",
        style: "ghost",
        external: true,
      },
      { label: "$ get --in-touch", href: "#contact", style: "ghost" },
    ],
  },

  about: {
    bio: [
      "Platform engineer focused on cloud-native infrastructure, automation, and scalable system architecture. I design and build platforms for high reliability, performance, and long-term evolution - end to end.",
      "Currently an <b>Associate Platform Engineer at Dataviva</b>, where I own Kubernetes infrastructure, CI/CD pipelines, and observability stacks for a cloud-native AI-driven retail platform.",
      "My philosophy: <b>automate everything, measure what matters, ship with confidence.</b> Great infrastructure is invisible.",
    ],
    stats: [
      { value: "1+", label: "Years Professional" },
      { value: "6+", label: "Projects Built" },
      { value: "Prod", label: "Infra Owner" },
      { value: "K8s", label: "Daily Driver" },
    ],
  },

  stack: [
    {
      icon: "☁️",
      name: "Cloud & Infrastructure",
      type: "tags",
      items: [
        "Kubernetes",
        "Docker",
        "Helm",
        "Terraform",
        "Ansible",
        "Azure (Primary)",
        "GCP (Exposure)",
        "AWS (Foundations)",
        "Linux",
      ],
    },
    {
      icon: "⚙️",
      name: "CI / CD & GitOps",
      type: "tags",
      items: [
        "GitHub Actions",
        "ArgoCD",
        "Jenkins",
        "GitOps",
        "Python",
        "Bash",
        "PowerShell",
      ],
    },
    {
      icon: "📊",
      name: "Observability & Testing",
      type: "tags",
      items: ["Prometheus", "Grafana", "Artillery", "Playwright", "MinIO", "SRE"],
    },
    {
      icon: "💻",
      name: "Core Proficiency",
      type: "bars",
      items: [
        { label: "Kubernetes", pct: 90 },
        { label: "Python", pct: 85 },
        { label: "JavaScript", pct: 80 },
        { label: "Java", pct: 75 },
        { label: "SQL", pct: 70 },
        { label: "Azure", pct: 60 },
      ],
    },
    {
      icon: "🏗️",
      name: "Architecture",
      type: "tags",
      items: [
        "Cloud-Native Design",
        "Microservices",
        "Distributed Systems",
        "RESTful APIs",
        "Event-Driven",
        "TOGAF",
        "Zachman",
        "BPMN",
        "Solution Architecture",
      ],
    },
    {
      icon: "🔧",
      name: "Dev & Data",
      type: "tags",
      items: [
        "Spring Boot",
        "Express.js",
        "React",
        "TypeScript",
        "Kafka",
        "PostgreSQL",
        "MySQL",
        "Android SDK",
        "PHP",
        "Apache",
      ],
    },
  ],

  projects: [
    {
      type: "platform tooling · production",
      name: "Cloud-Native Browser Load Testing Platform",
      desc: "Built the first distributed E2E load testing platform to run real Playwright browser sessions at scale on Kubernetes — replacing synthetic HTTP simulation with actual end-user workflows under full parallel load, orchestrated via Artillery. Owned the project end-to-end: architecture, implementation, client delivery, and production rollout. Architected a two-layer system with exact VU auto-splitting, wave-based execution, CSV batch injection, and six configurable load profiles. Includes a test generator with 35+ transformation rules, a visual verification suite with video capture, a zero-dependency reporting engine, and a native desktop GUI. Metrics flow through Prometheus and Grafana with SQLite regression tracking. Built and published via GitHub Actions to Azure Container Registry. Deployed to production at the highest concurrent real-browser VU count ever run on the system.",
      stack: [
        "Python",
        "Artillery",
        "Playwright",
        "Kubernetes",
        "Docker",
        "Azure Container Registry",
        "Prometheus",
        "Grafana",
        "MinIO",
        "SQLite",
        "GitHub Actions",
        "JavaScript",
      ],
      github: "https://github.com/AngelosFikias0",
    },
    {
      type: "enterprise · full-stack",
      name: "EfficienCity - Municipal Resource Management",
      desc: "Enterprise municipal platform designed end-to-end across the full SDLC. Led stakeholder mapping, BPMN AS-IS/TO-BE modeling, and SWOT/MoSCoW analysis. Architected a microservices system on Azure AKS with Kafka event-driven communication, ClickHouse analytics, an immutable audit ledger for full traceability, and a React + TypeScript MVP across three role-based interfaces.",
      stack: [
        "React",
        "TypeScript",
        "Spring Boot",
        "PostgreSQL",
        "ClickHouse",
        "Kafka",
        "Docker",
        "Azure AKS",
        "BPMN",
        "Figma",
      ],
      github: "https://github.com/AngelosFikias0/Resource_Management_System",
    },
    {
      type: "distributed systems · backend",
      name: "Java Network Services Hub",
      desc: "Multi-protocol distributed service framework supporting HTTP, TCP, UDP, and RMI communication. Implements concurrent request handling with thread pooling and a Swing-based orchestration interface for unified service management.",
      stack: [
        "Java",
        "Multi-threading",
        "Sockets",
        "RMI",
        "PostgreSQL",
        "Distributed Systems",
      ],
      github: "https://github.com/AngelosFikias0/Java_Network_Services_Hub",
    },
    {
      type: "enterprise architecture",
      name: "SafeCar - Enterprise Insurance Platform",
      desc: "Full-lifecycle insurance platform modeling the digital transformation of proposals, contracts, and claims. Applied TOGAF and Zachman frameworks to align software design with business strategy. Modeled workflows via BPMN and UML. Led team collaboration following SDLC best practices end-to-end.",
      stack: ["Java", "TOGAF", "Zachman", "BPMN", "UML", "Figma", "OOAD"],
      github: "https://github.com/AngelosFikias0/Safe_car_insurance_System",
    },
    {
      type: "mobile + backend",
      name: "TikiPark - Real-Time Smart Parking",
      desc: "Offline-first Android app with real-time slot synchronization, Google Maps integration, and SQLite caching for full network resilience. Modular backend with RBAC (Admin/User/Guest) and RESTful APIs ready for payment gateway extension.",
      stack: [
        "Java",
        "Android SDK",
        "PHP",
        "MySQL",
        "SQLite",
        "Google Maps API",
        "REST",
      ],
      github: "https://github.com/AngelosFikias0/TikiPark",
    },
    {
      type: "data engineering · graph analysis",
      name: "Crime Intelligence - Network Analysis Platform",
      desc: "Graph-based investigative intelligence platform using the JUNG library and advanced graph theory. Computes centrality metrics (betweenness, closeness, degree) to identify key suspects and uncover criminal relationship patterns.",
      stack: [
        "Java",
        "JUNG",
        "Graph Theory",
        "Swing",
        "Data Visualization",
        "MVC",
      ],
      github: "https://github.com/AngelosFikias0/Crime_Management_System",
    },
  ],

  experience: [
    {
      period: "JAN 2026 - PRESENT",
      role: "Associate Platform Engineer",
      company: "Dataviva · Thessaloniki, Greece",
      bullets: [
        "Built the first distributed E2E browser load testing platform on Kubernetes — real Playwright sessions at scale, wave-based execution, exact VU auto-splitting, and full observability stack. Deployed to production as first task.",
        "Own Kubernetes infrastructure, Docker deployments, CI/CD pipelines, and observability stacks across the platform.",
        "Automated image build and delivery pipelines via GitHub Actions to Azure Container Registry for air-gapped client deployments.",
        "Implemented Prometheus and Grafana observability with ServiceMonitor, custom dashboards, and SQLite-backed regression tracking.",
        "Drive platform efficiency, maintainability, and scalability across the SDLC in a fast-moving agile environment.",
      ],
      tags: [
        "Kubernetes",
        "Docker",
        "GitHub Actions",
        "Prometheus",
        "Grafana",
        "Azure",
        "Python",
        "Artillery",
        "Playwright",
      ],
    },
    {
      period: "OCT 2025 - DEC 2025",
      role: "DevOps Engineer Intern",
      company: "Dataviva · Thessaloniki, Greece",
      bullets: [
        "Developed and managed cloud-native infrastructure for an AI-driven retail forecasting platform.",
        "Operated and scaled Kubernetes clusters using Docker, Helm, and Linux.",
        "Began building distributed E2E performance testing infrastructure — continued and shipped as full-time first task.",
        "Built and automated internal tooling and scripts in Python and Bash.",
        "Collaborated in Agile workflows across infrastructure, backend, and platform teams.",
      ],
      tags: [
        "Kubernetes",
        "Linux",
        "Python",
        "JavaScript",
        "Bash",
        "PowerShell",
        "Agile",
      ],
    },
    {
      period: "OCT 2022 - PRESENT",
      role: "BSc. Applied Computer Science",
      company: "University of Macedonia · Thessaloniki, Greece · GPA 7.46",
      desc: "Specialization in Information Systems. Built expertise in software engineering, IT infrastructure, data, distributed systems, and digital strategy. Delivered business-driven solutions through team-based projects designing and optimizing scalable systems aligned with organizational objectives.",
      tags: [
        "Information Systems",
        "Distributed Systems",
        "System Design",
        "Solution Architecture",
        "Agile",
      ],
    },
  ],

  certifications: [
    {
      icon: "🔷",
      name: "Azure Fundamentals (AZ-900)",
      issuer: "Microsoft",
      date: "Jan 2026",
    },
    {
      icon: "☸️",
      name: "Manage Kubernetes in Google Cloud",
      issuer: "Google",
      date: "Dec 2025",
    },
    {
      icon: "☸️",
      name: "Introduction to Kubernetes",
      issuer: "The Linux Foundation",
      date: "Nov 2025",
    },
    {
      icon: "🔄",
      name: "Intro to CD & GitOps using Argo CD",
      issuer: "Akuity",
      date: "Nov 2025",
    },
    {
      icon: "🔧",
      name: "Introduction to Jenkins",
      issuer: "The Linux Foundation",
      date: "Nov 2025",
    },
    {
      icon: "🟠",
      name: "Serverless Fundamentals",
      issuer: "AWS",
      date: "Oct 2025",
    },
    {
      icon: "🔔",
      name: "DevOps Professional",
      issuer: "PagerDuty",
      date: "Sep 2025",
    },
    {
      icon: "🔄",
      name: "DevOps Foundations: CI/CD",
      issuer: "CompTIA",
      date: "Sep 2025",
    },
    {
      icon: "📋",
      name: "Agile Project Management Professional",
      issuer: "Atlassian",
      date: "Sep 2025",
    },
    {
      icon: "🔐",
      name: "Introduction to Cybersecurity",
      issuer: "Cisco",
      date: "Aug 2025",
    },
  ],

  contact: {
    intro:
      "Want to talk <b>Kubernetes internals, GitOps patterns, or cloud-native architecture</b>? Always happy to connect with engineers and teams building interesting things. Drop me a line.",
    openTo: [],
    languages: [
      { lang: "Greek", level: "Native" },
      { lang: "English", level: "C2 Proficiency" },
      { lang: "German", level: "Elementary" },
    ],
    links: [
      {
        icon: "✉️",
        platform: "Email",
        handle: "angelosfikias@gmail.com",
        href: "mailto:angelosfikias@gmail.com",
      },
      {
        icon: "gh",
        platform: "GitHub",
        handle: "@AngelosFikias0",
        href: "https://github.com/AngelosFikias0",
        external: true,
      },
      {
        icon: "li",
        platform: "LinkedIn",
        handle: "Angelos Fikias",
        href: "https://www.linkedin.com/in/angelos-fikias/",
        external: true,
      },
    ],
  },

  softSkills: [
    "Agile Collaboration",
    "Critical Thinking",
    "Continuous Learning",
    "Project Ownership",
    "Cross-Functional Communication",
    "Technical Communication",
    "Time Management",
    "Stakeholder Management",
  ],
};
