window.SITE_DATA = {
  meta: {
    name: "Angelos Fikias",
    role: "Associate Platform Engineer",
    company: "Dataviva",
    location: "Thessaloniki, Greece",
    email: "angelosfikias@gmail.com",
    github: "https://github.com/AngelosFikias0",
    linkedin: "https://www.linkedin.com/in/angelos-fikias/",
    status: "Shipping production infrastructure",
    focus: "Platform Engineering · DevOps · Cloud Infrastructure",
  },

  terminal: [
    { type: "cmd", text: "cat whoami.json" },
    { type: "blank" },
    { type: "brace", text: "{" },
    { type: "field", key: "name", value: "Angelos Fikias" },
    { type: "field", key: "role", value: "Associate Platform Engineer" },
    { type: "field", key: "company", value: "Dataviva" },
    { type: "field", key: "location", value: "Thessaloniki, Greece" },
    {
      type: "field",
      key: "focus",
      value: "Platform Engineering · DevOps · Cloud Infrastructure",
    },
    {
      type: "field",
      key: "education",
      value: "BSc Applied CS @ University of Macedonia",
      last: true,
    },
    { type: "brace", text: "}" },
  ],

  hero: {
    headline: ["Building ", "platforms", " that\nship with confidence."],
    sub: "I own cloud-native infrastructure end to end — Kubernetes, CI/CD, observability, and the automation that ties it together. Based in Thessaloniki, shipping to production.",
    ctas: [
      { label: "$ explore --projects", href: "#projects", style: "primary" },
      {
        label: "$ open github",
        href: "https://github.com/AngelosFikias0",
        style: "ghost",
        external: true,
      },
      { label: "$ get --in-touch", href: "#contact", style: "ghost" },
    ],
  },

  about: {
    bio: [
      "I'm a platform engineer focused on building and operating the infrastructure that lets product teams ship reliably and fast. My work spans Kubernetes cluster ownership, CI/CD pipeline design, observability stacks, and automation tooling — from the first commit to production rollout.",
      "Currently an <b>Associate Platform Engineer at Dataviva</b>, where I own Kubernetes infrastructure, CI/CD pipelines, and observability stacks for a cloud-native AI-driven retail platform.",
      "My philosophy: <b>automate everything, measure what matters, ship with confidence.</b> Great infrastructure is invisible — it's just the floor the whole team stands on.",
    ],
    stats: [
      { value: "1+", label: "Years Professional" },
      { value: "4+", label: "Projects Built" },
      { value: "Prod", label: "Infra Owner" },
      { value: "K8s", label: "Daily Driver" },
    ],
  },

  mainStack: [
    "Kubernetes",
    "Docker",
    "Azure",
    "CI/CD",
    "Java",
  ],

  stack: [
    {
      icon: "☁️",
      name: "Cloud & Infrastructure",
      type: "tags",
      items: [
        "Kubernetes",
        "Docker",
        "Helm",
        "Terraform",
        "Ansible",
        "Azure",
        "GCP",
        "AWS",
        "Linux",
      ],
    },
    {
      icon: "⚙️",
      name: "CI/CD & GitOps",
      type: "tags",
      items: [
        "GitHub Actions",
        "ArgoCD",
        "Jenkins",
        "GitOps",
        "Azure Container Registry",
      ],
    },
    {
      icon: "📊",
      name: "Observability & Data",
      type: "tags",
      items: [
        "Prometheus",
        "Grafana",
        "SQLite",
        "PostgreSQL",
        "ClickHouse",
        "Kafka",
        "MinIO",
      ],
    },
    {
      icon: "🧪",
      name: "Testing & Automation",
      type: "tags",
      items: [
        "Artillery",
        "Playwright",
        "Bash",
        "PowerShell",
      ],
    },
    {
      icon: "💻",
      name: "Languages & Frameworks",
      type: "tags",
      items: [
        "Python",
        "JavaScript",
        "TypeScript",
        "Java",
        "SQL",
        "React",
        "Spring Boot",
      ],
    },
  ],

  projects: [
    {
      type: "platform tooling · production",
      name: "Cloud-Native Browser Load Testing Platform",
      desc: "Built a distributed E2E load testing platform to run real Playwright browser sessions at scale on Kubernetes — replacing synthetic HTTP simulation with actual end-user workflows under full parallel load, orchestrated via Artillery. Owned the project end-to-end: architecture, implementation, client delivery, and production rollout. Architected a two-layer system with exact VU auto-splitting, wave-based execution, CSV batch injection, and six configurable load profiles. The platform includes an intelligent test generator powered by a Python engine and a structured JSON knowledge base: it detects and auto-fixes 35+ known Angular E2E pitfalls (timing issues, dynamic selectors, async rendering edge cases), and for patterns that cannot be resolved automatically, it surfaces targeted guidance — rewriting the problem, explaining the root cause, and providing testers with actionable steps toward stable, reliable implementations. Extended with a Helm-based environment lifecycle operator for autonomous namespace management: cluster-aware auto-discovery across four lookup strategies, full provision/status/destroy/cleanup lifecycle, and GUI-confirmed destructive actions. Includes a visual verification suite with video capture, a zero-dependency reporting engine, and a native desktop GUI. Metrics flow through Prometheus and Grafana with SQLite regression tracking. Built and published via GitHub Actions to Azure Container Registry. Deployed to production at the highest concurrent real-browser VU count ever run on the system.",
      stack: [
        "Python",
        "Artillery",
        "Playwright",
        "Kubernetes",
        "Helm",
        "Docker",
        "Azure Container Registry",
        "Prometheus",
        "Grafana",
        "MinIO",
        "SQLite",
        "GitHub Actions",
        "JavaScript",
      ],
      github: "https://github.com/AngelosFikias0",
    },
    {
      type: "enterprise · full-stack · university",
      name: "EfficienCity - Municipal Resource Management",
      desc: "Enterprise-grade municipal platform designed end-to-end from stakeholder analysis through cloud architecture, enabling inter-municipality asset sharing, real-time inventory tracking, and citizen-facing transparency. Led full systems analysis across the complete SDLC: stakeholder mapping, BPMN AS-IS/TO-BE modeling, Root Cause Analysis, SWOT, and MoSCoW prioritization. Designed a microservices system on Azure AKS with Kafka event-driven communication, multi-layer data pipeline across PostgreSQL and ClickHouse, and immutable audit ledger ensuring 100% transaction traceability and GDPR compliance. Delivered a React + TypeScript MVP across three role-based interfaces (Citizen, Municipal Employee, Administrator), designed in Figma with full UX journey documentation.",
      stack: [
        "React",
        "TypeScript",
        "Spring Boot",
        "PostgreSQL",
        "ClickHouse",
        "Kafka",
        "Docker",
        "Azure AKS",
        "BPMN",
        "Figma",
      ],
      github: "https://github.com/AngelosFikias0/Resource_Management_System",
    },
    {
      type: "enterprise architecture · university",
      name: "SafeCar - Enterprise Insurance Platform",
      desc: "Enterprise insurance platform managing the full policy lifecycle from proposals through claims. Applied TOGAF and Zachman frameworks to align software architecture with business strategy. Modeled the digital transformation of insurance processes end-to-end via BPMN and UML. Defined role-based access and automated workflows across a team-delivered SDLC project.",
      stack: [
        "Java",
        "TOGAF",
        "Zachman",
        "BPMN",
        "UML",
        "Figma",
        "Enterprise Architecture",
      ],
      github: "https://github.com/AngelosFikias0/Safe_car_insurance_System",
    },
    {
      type: "mobile + backend · university",
      name: "TikiPark - Real-Time Smart Parking",
      desc: "Smart Android parking assistant solving urban parking challenges with real-time slot availability, offline-first architecture, and seamless Google Maps integration. Architected offline-first system maintaining full functionality during network interruptions. Implemented RBAC with Admin/User/Guest tiers across a modular authentication system. Designed modular backend with RESTful APIs ready for payment gateway integration.",
      stack: [
        "Java",
        "Android SDK",
        "PHP",
        "MySQL",
        "SQLite",
        "Google Maps API",
        "REST",
      ],
      github: "https://github.com/AngelosFikias0/TikiPark",
    },
  ],

  experience: [
    {
      period: "JAN 2026 - PRESENT",
      role: "Associate Platform Engineer",
      company: "Dataviva · Thessaloniki, Greece",
      bullets: [
        "Built a distributed E2E browser load testing platform on Kubernetes — real Playwright sessions at scale, exact VU auto-splitting, wave-based execution, Helm-based environment lifecycle operator, and full observability stack. Deployed to production.",
        "Own Kubernetes infrastructure, Docker deployments, CI/CD pipelines, and observability stacks across the platform.",
        "Automated image build and delivery pipelines via GitHub Actions to Azure Container Registry for air-gapped client deployments.",
        "Implemented Prometheus and Grafana observability with ServiceMonitor, custom dashboards, and SQLite-backed regression tracking.",
        "Drive platform efficiency, maintainability, and scalability across the SDLC in a fast-moving agile environment.",
      ],
      tags: [
        "Kubernetes",
        "Helm",
        "Docker",
        "GitHub Actions",
        "Prometheus",
        "Grafana",
        "Azure",
        "Python",
        "Artillery",
        "Playwright",
      ],
    },
    {
      period: "OCT 2025 - DEC 2025",
      role: "DevOps Engineer Intern",
      company: "Dataviva · Thessaloniki, Greece",
      bullets: [
        "Developed and managed cloud-native infrastructure for an AI-driven retail forecasting platform.",
        "Operated and scaled Kubernetes clusters using Docker, Helm, and Linux.",
        "Began building distributed E2E performance testing infrastructure — continued and shipped as full-time first task.",
        "Built and automated internal tooling and scripts in Python and Bash.",
        "Collaborated in Agile workflows across infrastructure, backend, and platform teams.",
      ],
      tags: [
        "Kubernetes",
        "Linux",
        "Python",
        "JavaScript",
        "Bash",
        "PowerShell",
        "Agile",
      ],
    },
    {
      period: "OCT 2022 - PRESENT",
      role: "BSc. Applied Computer Science",
      company: "University of Macedonia · Thessaloniki, Greece · GPA 7.46",
      desc: "Specialization in Information Systems. Built expertise in software engineering, IT infrastructure, data, distributed systems, and digital strategy. Delivered business-driven solutions through team-based projects designing and optimizing scalable systems aligned with organizational objectives.",
      tags: [
        "Information Systems",
        "Distributed Systems",
        "System Design",
        "Solution Architecture",
        "Agile",
      ],
    },
  ],

  certifications: [
    // ── Cloud & Kubernetes ──
    {
      icon: "🔷",
      name: "Azure Fundamentals (AZ-900)",
      issuer: "Microsoft",
      date: "Jan 2026",
    },
    {
      icon: "☸️",
      name: "Manage Kubernetes in Google Cloud",
      issuer: "Google",
      date: "Dec 2025",
    },
    {
      icon: "☸️",
      name: "Introduction to Kubernetes",
      issuer: "The Linux Foundation",
      date: "Nov 2025",
    },
    // ── DevOps & CI/CD ──
    {
      icon: "🔔",
      name: "DevOps Professional",
      issuer: "PagerDuty",
      date: "Sep 2025",
    },
    {
      icon: "🔄",
      name: "Intro to CD & GitOps using Argo CD",
      issuer: "Akuity",
      date: "Nov 2025",
    },
    {
      icon: "🔧",
      name: "Introduction to Jenkins",
      issuer: "The Linux Foundation",
      date: "Nov 2025",
    },
    {
      icon: "🔄",
      name: "DevOps Foundations: Site Reliability Engineering",
      issuer: "LinkedIn",
      date: "Sep 2025",
    },
    // ── Architecture & Agile ──
    {
      icon: "📋",
      name: "Agile Project Management Professional",
      issuer: "Atlassian",
      date: "Sep 2025",
    },
    {
      icon: "🏗️",
      name: "Software Architecture Foundations",
      issuer: "LinkedIn",
      date: "Aug 2025",
    },
    {
      icon: "🏗️",
      name: "Enterprise Architecture Foundations",
      issuer: "LinkedIn",
      date: "Aug 2025",
    },
    // ── Security & Languages ──
    {
      icon: "🔐",
      name: "Introduction to Cybersecurity",
      issuer: "Cisco",
      date: "Aug 2025",
    },
    {
      icon: "☕",
      name: "Oracle Java Foundations",
      issuer: "Oracle",
      date: "Aug 2025",
    },
  ],

  contact: {
    intro:
      "Want to talk <b>Kubernetes internals, GitOps patterns, or cloud-native architecture</b>? Always happy to connect with engineers and teams building interesting things. Drop me a line.",
    languages: [
      { lang: "Greek", level: "Native" },
      { lang: "English", level: "C2 Proficiency" },
      { lang: "German", level: "Elementary" },
    ],
    links: [
      {
        icon: "✉️",
        platform: "Email",
        handle: "angelosfikias@gmail.com",
        href: "mailto:angelosfikias@gmail.com",
      },
      {
        icon: "gh",
        platform: "GitHub",
        handle: "@AngelosFikias0",
        href: "https://github.com/AngelosFikias0",
        external: true,
      },
      {
        icon: "li",
        platform: "LinkedIn",
        handle: "Angelos Fikias",
        href: "https://www.linkedin.com/in/angelos-fikias/",
        external: true,
      },
    ],
  },
};
